### PR TITLE
fixed cannot find epoxy error in cmake

### PR DESCRIPTION
**Pull request by dyumanaditya**
Hello,

Thank you for your package, I found an error while building that was due to an incorrect filename: `FIndepoxy.cmake` should be `Findepoxy.cmake`. This allowed me to build locally and solves the following build error:

```
CMake Error at CMakeLists.txt:33 (find_package):
  By not providing "Findepoxy.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "epoxy", but
  CMake did not find one.

  Could not find a package configuration file provided by "epoxy" with any of
  the following names:

    epoxyConfig.cmake
    epoxy-config.cmake

  Add the installation prefix of "epoxy" to CMAKE_PREFIX_PATH or set
  "epoxy_DIR" to a directory containing one of the above files.  If "epoxy"
  provides a separate development package or SDK, be sure it has been
  installed.
  ```

### CODE REVIEW

**Comment by jnskkmhr** [comment]
@dyumanaditya 
Hi, thanks for pointing this out !!
This explains why I needed to set the CMakeModules path from OS3 even though it is set in the ROS2 wrapper. 
https://github.com/jnskkmhr/orbslam3/blob/e9e05bc96cf8572e117b73fda14054e7d3bb2bda/CMakeLists.txt#L11

**Comment by BCaran** [comment]
When _colcon build_ - ing, I am getting this error about GetCurrentFrame()

`home/wcr/os3_ws/src/orbslam3/src/stereo-inertial/stereo-inertial-node.cpp: In member function ‘void StereoInertialNode::SyncWithImu()’:
/home/wcr/os3_ws/src/orbslam3/src/stereo-inertial/stereo-inertial-node.cpp:280:83: error: ‘class ORB_SLAM3::System’ has no member named ‘GetCurrentFrame’
  280 |             publish_tracking_img(pubTrackImage_, this->get_clock()->now(), SLAM_->GetCurrentFrame(), world_frame);
      |                                                                                   ^~~~~~~~~~~~~~~
/home/wcr/os3_ws/src/orbslam3/src/stereo/stereo-slam-node.cpp: In member function ‘void StereoSlamNode::GrabStereo(sensor_msgs::msg::Image_<std::allocator<void> >::SharedPtr, sensor_msgs::msg::Image_<std::allocator<void> >::SharedPtr)’:
/home/wcr/os3_ws/src/orbslam3/src/stereo/stereo-slam-node.cpp:159:76: error: ‘class ORB_SLAM3::System’ has no member named ‘GetCurrentFrame’
  159 |     publish_tracking_img(pubTrackImage_, this->get_clock()->now(), m_SLAM->GetCurrentFrame(), world_frame);
      |                                                                            ^~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/stereo.dir/build.make:76: CMakeFiles/stereo.dir/src/stereo/stereo-slam-node.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/stereo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/stereo-inertial.dir/build.make:76: CMakeFiles/stereo-inertial.dir/src/stereo-inertial/stereo-inertial-node.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/stereo-inertial.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Failed   <<< orbslam3 [1min 12s, exited with code 2]`

**Comment by dyumanaditya** [comment]
That's because you haven't installed the correct version of ORB_SLAM3. It's this: https://github.com/jnskkmhr/ORB-SLAM3-STEREO-FIXED.

As the owner of the repo suggests, it's better to use his docker image unless you know for sure what you're doing.

**Comment by BCaran** [comment]
Ohh, I installed https://github.com/zang09/ORB-SLAM3-STEREO-FIXED, haven't seen that he has made there some commits.

Sorry.

**Pull request merged**
